### ISSUE TITLE
unknown file format when using clotho dataset

### ISSUE THREAD

**Issue by arunodhayan** [audio-captioning/dcase-2020-baseline#4]
RuntimeError: Error opening 'data/clotho_audio_files/development/Distorted AM Radio noise.wav': File contains data in an unknown format.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 57, in <module>
    main()
  File "main.py", line 40, in main
    settings_dirs_and_files=settings['dirs_and_files'])
  File "/src/processes/dataset.py", line 111, in create_dataset
    dir_downloaded_audio)
  File "/src/tools/dataset_creation.py", line 288, in create_split_data
    mono=settings_audio['to_mono'])
  File "/src/tools/file_io.py", line 83, in load_audio_file
    offset=offset, duration=duration)[0]
  File "/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py", line 147, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py", line 171, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "/usr/local/lib/python3.7/dist-packages/audioread/__init__.py", line 116, in audio_open
    raise NoBackendError()
audioread.exceptions.NoBackendError

**Comment by dr-costas** [comment]
Hi, 

I have seen this issue before, and it was an issue of the decompression of the 7zip archive. Please note that the archive **is not** `.zip` but `.7z`. They are not the same. 

If you are in Linux O.S., then try installing a 7zip package (e.g. `p7zip`). If you are in MAC O.S., try using apps that can expand 7zip archives (e.g. Unarchiver). I cannot help you for Windows O.S.

Let me know if you were able to expand the archive.

**Comment by arunodhayan** [comment]
yes it worked well thank you so much

**Comment by dr-costas** [comment]
Thank you too for letting us know. 

I'm closing this issue, please feel free to create another one if something else comes up.
